This Notebook is to perform EDA on the COVID datasets and to group the data so that it can be compared to the air quality and CO2 data

In [1]:
import pandas as pd

In [2]:
covid_cases_df = pd.read_csv(".\data\county_covid_cases.csv")
covid_deaths_df = pd.read_csv(".\data\county_covid_deaths.csv")
census_df = pd.read_csv(".\data\county_population_census.csv", encoding = "ISO-8859-1")

Take a look at the dataframes

In [3]:
covid_cases_df.head()

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,9/16/20,9/17/20,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20,9/24/20,9/25/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,1619,1624,1664,1673,1690,1691,1714,1715,1757,1764
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,5003,5021,5033,5047,5061,5087,5124,5141,5456,5477
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,809,809,824,830,835,838,848,851,873,882
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,612,617,619,628,632,635,635,638,652,654

In [4]:
covid_deaths_df.head()

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,9/16/20,9/17/20,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20,9/24/20,9/25/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,24,24,24,24,24,24,25,25,25,25
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,47,48,48,49,49,49,49,49,50,50
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,9,9,10,10,10,10,10,10,10,10

In [5]:
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,40,3,6,1,0,Alabama,Alabama,4779736,4780125,4785437,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
1,50,3,6,1,1,Alabama,Autauga County,54571,54597,54773,...,4.847310,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183112,...,24.017829,16.641870,17.488579,22.751474,20.184334,17.725964,21.279291,22.398256,24.727215,24.380567
3,50,3,6,1,5,Alabama,Barbour County,27457,27455,27327,...,-5.690302,0.292676,-6.897817,-8.132185,-5.140431,-15.724575,-18.238016,-24.998528,-8.754922,-5.165664
4,50,3,6,1,7,Alabama,Bibb County,22915,22915,22870,...,1.385134,-4.998356,-3.787545,-5.797999,1.331144,1.329817,-0.708717,-3.234669,-6.857092,1.831952

Because our CO2 data is at the state level, we will want some of this data to be grouped by state so it can be spatially compared to the air quality

In [6]:
state_cases_df = covid_cases_df.groupby(by = ["State"]).sum()

#the sum of countyFIPS and stateFIPS is not helpful to us here - let's remove it
state_cases_df.drop(columns = ["countyFIPS", "stateFIPS"], inplace = True)

#Next, we want the State column to be it's own column instead of the row index. 
state_cases_df = state_cases_df.reset_index()

In [7]:
#Do the same thing to the deaths dataframe
state_deaths_df = covid_deaths_df.groupby(by = ["State"]).sum()
state_deaths_df.drop(columns = ["countyFIPS", "stateFIPS"], inplace = True)
state_deaths_df = state_deaths_df.reset_index()

Now we have the number of COVID cases and deaths for each state... but should we really compare the number of cases in California with the number of cases in Montana? Here, I am joining the census data to our state-level COVID dataframes to standardize the counts

In [8]:
#Instead of lookiing at all of the county-level populations,we can just take the state-level because our other data is also at the state level 
state_populations_df = census_df[census_df["STNAME"] == census_df["CTYNAME"]]

#There are two rows of "District of Columbia" with the same values... delete one of them
state_populations_df = state_populations_df.drop(index = 327)

#reindex the dataframe
state_populations_df.reset_index(inplace = True)

Next, we have to merge the state populations onto the COVID dataframes  

Because one dataframe has the state name and the other has the abbreviation, we need to modify the data first  
Map found from Roger Allen's github to save time :)  https://gist.github.com/rogerallen/1583593

In [9]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

state_populations_df = state_populations_df.replace({"STNAME": us_state_abbrev})

#Let's also drop all of the columns of census data that we don't need...
state_populations_df = state_populations_df[["STNAME", "POPESTIMATE2019"]]

In [10]:
#Merge the data together
state_cases_pop_df = state_cases_df.merge(right = state_populations_df, left_on = ["State"], right_on = ["STNAME"])
state_cases_pop_df = state_cases_pop_df.drop(columns = "STNAME")

In [20]:
#First, we will get a list of all of the columns that we are going to transform - all of the dates with COVID observations
df_cols = list(state_cases_pop_df.columns.values)
df_cols.remove('State')
df_cols.remove('POPESTIMATE2019')

state_cases_pop_df[df_cols] = state_cases_pop_df[df_cols].apply(pd.to_numeric)
#Make a copy that we can modify
state_cases_corrected = state_cases_pop_df.copy(deep = True)


#divide the COVID count in each column by the Population in its row  * 100
#It will represent the COVID cases 
for col in df_cols:
    state_cases_corrected.loc[:, col] = (state_cases_corrected.loc[:, col] / state_cases_corrected.loc[:, "POPESTIMATE2019"]) * 100

This final table shows the percent of the population that has COVID by state

In [21]:
state_cases_corrected.head()

,State,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,9/17/20,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20,9/24/20,9/25/20,POPESTIMATE2019
0,AK,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.895229,0.910129,0.921748,0.934324,0.943893,0.950044,0.957426,0.974923,0.991600,731545
1,AL,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.891100,2.913637,2.940211,2.956446,2.973088,2.989445,3.001172,3.072513,3.091684,4903185
2,AR,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.425903,2.454765,2.490553,2.509043,2.530416,2.550861,2.583435,2.619421,2.649145,3017804
3,AZ,0.0,0.0,0.0,0.0,0.000014,0.000014,0.000014,0.000014,0.000014,...,2.907490,2.925186,2.933855,2.940298,2.945602,2.951647,2.957719,2.965523,2.972598,7278717
4,CA,0.0,0.0,0.0,0.0,0.000005,0.000008,0.000008,0.000010,0.000010,...,1.962534,1.973723,1.982913,1.987995,2.000437,2.007607,2.016034,2.024146,2.034497,39512223

Now that we have standardized the COVID cases data by population, we will do the same thing to the deaths data

In [22]:
#Merge the data together
state_deaths_pop_df = state_deaths_df.merge(right = state_populations_df, left_on = ["State"], right_on = ["STNAME"])
state_deaths_pop_df = state_deaths_pop_df.drop(columns = "STNAME")

In [24]:
#First, we will get a list of all of the columns that we are going to transform - all of the dates with COVID observations
death_df_cols = list(state_deaths_pop_df.columns.values)
death_df_cols.remove('State')
death_df_cols.remove('POPESTIMATE2019')

state_deaths_pop_df[death_df_cols] = state_deaths_pop_df[death_df_cols].apply(pd.to_numeric)
#Make a copy that we can modify
state_deaths_corrected = state_deaths_pop_df.copy(deep = True)


#divide the COVID death count in each column by the Population in its row  * 100
#It will represent the COVID deaths 
for col in death_df_cols:
    state_deaths_corrected.loc[:, col] = (state_deaths_corrected.loc[:, col] / state_deaths_corrected.loc[:, "POPESTIMATE2019"]) * 100

In [125]:
state_deaths_corrected

,State,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20,9/24/20,9/25/20,POPESTIMATE2019,Sum Cases
0,AK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.151365,6.151365,6.151365,6.151365,6.151365,6.151365,6.288062,7.108244,731545,465.589950
1,AL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,49.416859,49.600413,49.600413,49.641203,49.987916,50.660948,50.742528,51.007661,4903185,4026.199297
2,AR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,38.869324,39.134417,39.134417,39.664604,40.062244,40.724978,41.288301,41.951035,3017804,2171.347112
3,AZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,74.889572,75.095652,75.205562,75.233039,75.452858,75.892496,76.373350,76.758033,7278717,5669.556874
4,CA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,37.740220,37.930035,38.008492,38.137566,38.476701,38.755096,38.970219,39.314417,39512223,3104.039477
5,CO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.868763,34.938223,34.955587,35.042412,35.163967,35.250791,35.302886,35.372346,5758736,4480.167176
6,CT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,125.992662,125.992662,125.992662,126.076807,126.104855,126.132903,126.189000,126.245096,3565287,18012.182469
7,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,87.283156,87.283156,87.849930,87.991623,87.991623,87.991623,87.991623,88.275010,705749,11467.958155
8,DE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.670458,63.773152,63.773152,64.389318,64.492012,64.594707,64.697401,64.800095,973764,7560.558821
9,FL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,61.570733,61.854748,61.905963,61.999083,62.464681,63.405190,64.229299,64.788017,21477737,4288.338199
10,GA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,61.549775,62.133721,62.161977,62.180814,62.858944,63.763118,64.252879,64.742640,10617423,5120.112479
11,HI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.475342,8.475342,8.475342,8.475342,8.475342,8.616598,8.757854,8.969737,1415872,407.310830
12,IA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,39.872332,40.062503,40.094198,40.125893,40.728098,40.981658,41.171828,41.298608,3155070,3707.176069
13,ID,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.509461,24.677334,24.733292,24.845207,25.180953,25.348826,25.516699,25.628615,1787065,1602.403942
14,IL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,66.375622,66.572910,66.683391,66.738632,66.967486,67.141100,67.377846,67.575134,12671821,8045.836506
15,IN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,51.869970,52.003656,52.048218,52.137341,52.285881,52.434420,52.701791,52.969162,6732219,5810.060546
16,KS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.526452,20.526452,20.526452,20.595102,20.835379,21.315931,21.659183,21.693508,2913314,1753.398364
17,KY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.621319,24.778000,24.845149,24.867532,25.024213,25.136128,25.427107,25.718086,4467673,2274.495022
18,LA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,111.254661,111.254661,111.792435,111.964522,112.201143,112.373231,112.738917,113.190647,4648794,12072.808561
19,MA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,134.479448,134.856670,135.074297,135.175857,135.335451,135.335451,135.828740,135.973825,6892503,17503.757343
20,MD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,64.922391,65.038176,65.120880,65.153961,65.319369,65.468235,65.567480,65.732887,6045680,7806.135952
21,ME,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.266238,10.340631,10.340631,10.415024,10.415024,10.415024,10.415024,10.415024,1344212,1260.887420
22,MI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,69.631517,69.771701,69.771701,69.881846,70.032043,70.182241,70.272359,70.362477,9986857,9626.902638
23,MN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.576724,34.807236,34.842699,34.913626,35.090942,35.197332,35.250527,35.356917,5639632,3757.922503
24,MO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29.002377,29.214192,29.246779,29.426007,30.354735,31.658213,31.788560,32.489180,6137428,2755.877543
25,MS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,93.778907,94.316514,94.350115,94.350115,95.492531,96.298942,96.567746,97.239755,2976149,7372.681946
26,MT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.847590,14.783238,14.876803,15.157498,15.438192,15.625322,15.625322,16.093146,1068778,808.212744
27,NC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30.577558,30.825459,30.911270,30.949409,31.330794,31.616833,31.998218,32.503554,10488084,2447.282077
28,ND,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.145017,25.194800,25.194800,25.326023,25.719692,26.638253,27.688036,27.688036,762062,1939.999633
29,NE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.901063,22.901063,22.901063,23.314626,23.728190,23.883276,23.934971,24.245144,1934408,2166.089057
30,NH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,32.212728,32.212728,32.212728,32.212728,32.212728,32.212728,32.212728,32.212728,1359711,3821.253193
31,NJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,180.800005,180.833781,180.856298,180.867556,180.946366,181.025175,181.149018,181.227828,8882190,24450.929332
32,NM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.108182,40.394329,40.489711,40.585093,40.728166,40.871239,40.966622,41.252768,2096829,3937.993990
33,NV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,49.478013,49.607877,49.672809,49.705275,49.705275,50.192263,50.776649,51.068842,3080156,3853.733382
34,NY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,168.488433,168.529556,168.560399,168.586101,168.580961,168.591241,168.616944,168.678629,19453561,25838.169166
35,OH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,39.412786,39.455561,39.481226,39.549666,39.652326,40.097185,40.336724,40.499269,11689100,3988.356674
36,OK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.730272,23.806088,23.881904,23.932447,24.311525,24.513700,24.791690,25.094953,3956971,2036.456674
37,OR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.328886,12.328886,12.352596,12.518561,12.589690,12.731946,12.779365,12.850493,4217737,1042.928945
38,PA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,61.974745,62.146593,62.334064,62.521535,62.669949,62.974589,63.107381,63.123004,12801989,7700.647142
39,RI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,99.588337,99.588337,99.588337,99.588337,99.588337,101.759457,101.759457,101.759457,1059361,12486.395100
40,SC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,61.627039,61.840685,62.073753,62.306821,62.870068,63.355626,63.666383,64.035408,5148714,4144.549493
41,SD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.381505,22.607581,22.833657,22.833657,22.833657,22.833657,23.737960,24.416187,884659,1875.411882
42,TN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,32.097586,32.405090,32.434376,32.654022,33.064028,33.283674,33.810824,34.440476,6829174,2146.306420
43,TX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,50.714100,51.183132,51.341775,51.424545,51.690100,52.155684,52.635062,52.959246,28995881,3054.544195
44,UT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.630871,13.724447,13.724447,13.755639,13.818023,13.849214,13.849214,13.973982,3205958,1146.958257
45,VA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.514597,34.994943,35.276121,35.346415,35.815045,36.178234,36.459412,36.740590,8535519,3405.428539
46,VT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.295036,9.295036,9.295036,9.295036,9.295036,9.295036,9.295036,9.295036,623989,1494.417370
47,WA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.737080,26.737080,26.737080,26.723947,27.131044,27.288630,27.354291,27.551274,7614893,3093.740122
48,WI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.245410,21.296935,21.314110,21.348460,21.485860,21.623259,21.726309,21.880883,5822434,2211.635203
49,WV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.572301,17.186090,17.297688,17.409286,17.688281,17.799879,18.134673,18.413668,1792147,1112.799341
50,WY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.466391,8.466391,8.466391,8.466391,8.466391,8.466391,8.639175,8.639175,578759,641.026749